### ISSUE TITLE
Clicking debug button doesn't work and causes errors

### ISSUE THREAD

**Issue by dscowan** [livehouse-automation/veraflux#18] opened 2020-12-01 03:33 UTC
Trying to enable debug via the button and get these messages in the log.  Debug is never enabled

`
10	11/30/20 21:19:35.206	mg_callback from IP:127.0.0.1:54568 /port_3480/data_request id=lu_action&output_format=json&DeviceNum=172&serviceId=urn:livehouse-automation:serviceId:VeraFlux1&action=SetDebug&newDebugValue=1 start id: 384 <0x74710520>
12	11/30/20 21:19:35.206	luvd_get_info_data_request starting /data_request?id=lu_action&output_format=json&DeviceNum=172&serviceId=urn:livehouse-automation:serviceId:VeraFlux1&action=SetDebug&newDebugValue=1 pMem 0x151a000/22126592 diff: 11583488 <0x74710520>
08	11/30/20 21:19:35.208	JobHandler_LuaUPnP::HandleActionRequest device: 172 service: urn:livehouse-automation:serviceId:VeraFlux1 action: SetDebug <0x74710520>
08	11/30/20 21:19:35.209	JobHandler_LuaUPnP::HandleActionRequest argument serviceId=urn:livehouse-automation:serviceId:VeraFlux1 <0x74710520>
02	11/30/20 21:19:35.211	JobHandler_LuaUPnP::RunAction device 172 action urn:livehouse-automation:serviceId:VeraFlux1/SetDebug failed with -911/Device not ready <0x74710520>`

**Comment by antonywinn** [comment] 2020-12-08 00:15
I'm unable to reproduce this issue. There was an issue with UI buttons in the original version, but this is fixed in the current release. 

Make sure you're using the files from this Github repo, especially S_VeraFlux1.xml

**Closed as completed** 2021-02-06 06:14 UTC
